name: Common Workflow
on:
  workflow_call:
    inputs:
      version: # the variable you can use in place of a matrix
        required: true
        type: string
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: echo "matrix={\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}" >> $GITHUB_OUTPUT
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.job1.outputs.matrix) }}
    steps:
      - run: echo "Matrix - Project ${{ matrix.project }}, Config ${{ matrix.config }}"

#
#on:
#  workflow_call:
#    inputs:
#      version: # the variable you can use in place of a matrix
#        required: true
#        type: string
#
#jobs:
#  job0:
#    name: ${{matrix.repos.beamline}}
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        repos:
#          - beamline: srx
#            conclusion: na
#          - beamline: csx
#            conclusion: success
#    steps:
#      - run: |
#          echo ${{ matrix.repos.beamline }}
#          echo ${{ matrix.repos.conclusion }}
#      - name: Adding markdown
#        run: echo '### Hello world!' >> $GITHUB_STEP_SUMMARY
#    steps:
#      - name: Put thing into env var
#        run: |
#          export CONDA_PACK_ENV_NAME=${{env.s}}
#          echo "CONDA_PACK_ENV_NAME=${CONDA_PACK_ENV_NAME}" >> $GITHUB_ENV
#      - name: Output vars
#        id: otpt-something
#        run: |
#          num=hello
#          echo "SOMETHING=$num" >> $GITHUB_OUTPUT
#      - name: Create txt
#        run: touch ${{ inputs.version }}.txt
#      - name: upload txt as artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: ${{ inputs.version }}
#          path: ${{ inputs.version }}.txt

#  job1:
#    strategy:
#      fail-fast: false
#      matrix:
#        repos: [ { org: "NSLS-II-CSX", repo: "profile_collection", branch: "master", profile_branch: "qserver", beamline_acronym: "csx" },
#                 { org: "NSLS-II-SRX", repo: "profile_collection", branch: "master", profile_branch: "master", beamline_acronym: "srx" } ]
#    runs-on: ubuntu-latest
#    needs: job0
#    steps:
#      - run: |
#          echo "${{needs.job0.result}}"
#          echo "${{needs.job0.outputs.job0-id}}"

#      - run: echo 'job1 version ${{ inputs.version }} and ${{matrix.repos.org}}'
#      - name: Downloading Conda Artifact
#        uses: actions/download-artifact@v4
#        with:
#          name: ${{ inputs.version }}
#      - name: confirm download
#        run: ls
# something