on:
  workflow_call:
    inputs:
      version: # the variable you can use in place of a matrix
        required: true
        type: string
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      test_matrix: toJson(["1", "2", "3"])
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.job1.outputs.test_matrix }}
