on:
  workflow_call:
    inputs:
      version: # the variable you can use in place of a matrix
        required: true
        type: string
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
#      - name: print file
#        run: cat "matrix_json.yml"
      - id: set-matrix
#        run: echo "matrix={\"include\":[{\"repos\":{\"name\":\"csx\",\"org\":\"NSLS-II-CSX\",\"acronym\":csx}},{\"repos\":{\"name\":\"srx\",\"org\":\"NSLS-II-SRX\",\"acronym\":srx}}]}" >> $GITHUB_OUTPUT
        run: |
          python3 yml_to_string.py
          echo $LINK_STR
          echo "matrix={"include":[{"project":{"name":"foo","a":1,"b":2}},{"project":{"name":"bar","a":3,"b":4}}]}" >> $GITHUB_OUTPUT

#          echo "matrix={${LINK_STR}}" >> $GITHUB_OUTPUT
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.job1.outputs.matrix) }}
    steps:
      - run: |
          echo "Matrix - Project ${{ matrix.repos.a }}"
          echo "Matrix - Project ${{ matrix.repos.name }}"
          echo "Matrix - Project ${{ matrix.repos.b }}"
#          echo "Matrix - Project ${{ matrix.repos.name }}"
#          echo "Matrix - Project ${{ matrix.repos.acronym }}"

