name: Test Workflow

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
jobs:
  job-one:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python-version: ["3.10", "3.11", "3.12"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Print names
        run: echo ${{ matrix.python-version }}

#        repos: [ { org: "NSLS-II-CSX", repo: "profile_collection", branch: "master", profile_branch: "qserver", beamline_acronym: "csx" },
#                 { org: "NSLS-II-SRX", repo: "profile_collection", branch: "master", profile_branch: "master", beamline_acronym: "srx" } ]