on:
  workflow_call:
    inputs:
      version: # the variable you can use in place of a matrix
        required: true
        type: string
jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Test out test-action
        uses: StaticYolt/testing-conda-environment@v1.0.0
        with:
          python-version: ${{ inputs.version }}
          org: "NSLS-II-CSX"
          repo: "profile_collections"
          branch: "master"
          beamline-acronym: "csx"