on:
  workflow_call:
    inputs:
      version: # the variable you can use in place of a matrix
        required: true
        type: string
jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Test out test-action
        uses: StaticYolt/sy-test-action@v2
        with:
          python-version: ${{ inputs.version }}