on:
  push:
  workflow_dispatch:

jobs:
  upload-zenodo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: action/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Upload artifacts to Zenodo
        run: |
          python3 -m pip install requests
          python3 upload_artifacts.py