on:
#  push:
  workflow_dispatch:

jobs:
  upload-zenodo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set env vars
        run: |
          export ZENODO_TOKEN=${{ secrets.ZENODO_TOKEN }}
          echo "ZENODO_TOKEN=${ZENODO_TOKEN}" >> $GITHUB_ENV
          
          export GHA_TOKEN=${{github.token}}
          echo "GHA_TOKEN=${GHA_TOKEN}" >> $GITHUB_ENV
          
          export GH_TOKEN=${{github.token}}
          echo "GH_TOKEN=${GH_TOKEN}" >> $GITHUB_ENV
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Upload artifacts to Zenodo
        run: |
          python3 -m pip install requests
          python3 upload_artifacts.py